# Generated by Django 4.1.7 on 2023-03-06 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioEnvia', models.CharField(max_length=50)),
                ('usuarioRecibe', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 6, 18, 8, 0, 206279))),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('Baja', 'De 4 a 5 días'), ('Intermedio', 'De 2 a 3 días'), ('Alta', 'De 12hrs a 1 día')], max_length=20)),
            ],
        ),
    ]
