# Generated by Django 4.1.7 on 2023-03-10 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='usuarioEnvia',
            new_name='envia',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='usuarioRecibe',
            new_name='recibe',
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 10, 11, 21, 13, 16137)),
        ),
    ]
