# Generated by Django 4.1.2 on 2023-03-11 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_usuarioenvia_task_envia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 11, 11, 29, 16, 230569)),
        ),
    ]
